version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - '8000:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '4444:4444'
    network_mode: 'host'
    depends_on:
      mysql-db:
        condition: service_healthy
  mysql-db:
    image: mysql:latest
    restart: always
    command: --init-file /data/application/init.sql
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-volume:/var/lib/mysql
      - ./mysql-init-database/init.sql:/data/application/init.sql
    healthcheck:
      test: "exit 0"
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
